Refs #35885 - fix tests undefined method `[]' for nil:NilClass
in case that `result['invocation']` is nil:
foreman_ansible/app/helpers/foreman_ansible/ansible_reports_helper.rb:98:in `block in get_results'