Fixes #35885 - Error printing report with multiple results (#583)
* Fixes #35885 - Error printing report with multiple results

If Ansible job reported more than one results per action
then the config report page will fail to render. For example,
a task uses the Ansible copy module to copy multiple files
in a loop.

* Refs #35885 - fix rubocop issue

RuboCop::Cop::Lint::ShadowingOuterLocalVariable

module_args was in the `ansible_module_message` method scop,
and also as a parameter in the `get_results` function's signature

decided to remove the first definition of it as it wasn't used.

* Refs #35885 -  `end` was ommited during rebase

* Refs #35885 - fix tests undefined method `[]' for nil:NilClass

in case that `result['invocation']` is nil:
foreman_ansible/app/helpers/foreman_ansible/ansible_reports_helper.rb:98:in `block in get_results'

Co-authored-by: Ron Lavi <1ronlavi@gmail.com>

(cherry picked from commit ed16127d1b23233e42428d1eb0f4b0244a9a4bec)