Fixes #36136 - make sure validatorRule is a string (#601)
* Fixes #36136 - make sure validatorRule is a string

variable.validatorRule.split was raising a TypeError:
string.split is not a function

(cherry picked from commit bba4f31e6955b0833973cda768461a9521aca6a6)

* Updated REX and foreman-tasks dependencies

---------

Co-authored-by: Ron Lavi <1ronlavi@gmail.com>